### ISSUE TITLE
App wasn't watching for updates and running builds - but we figured out why.

### ISSUE THREAD

**Issue by jesseyuen** [fofr/govuk-design-history#141]
This week we're setting up a fresh design history and noticed the app wasn't watching for updates and running builds automatically. 

We had to run the app with `npx eleventy --serve` instead of `npm-start` as per the documentation outlined here: https://x-govuk.github.io/govuk-eleventy-plugin/get-started/ to get the app to watch for updates.

Is the intention that this repo is no longer to be used and the GOV.UK Eleventy Plugin is the preferred tool? 

😘  Jesse

**Comment by frankieroberto** [comment]
@jesseyuen this repo is still used - it now has the `govuk-eleventy-plugin` plugin as a dependency, but adds some additional features to support design histories (for example the "email" and "screenshots" components).

It looks like the app is currently set up with 2 ways to start it:

* `npm start` - runs the `http-server` npm module, which I guess is intended for "production" environments like Heroku, ie no watching of files?
* `npm run dev` - runs `eleventy --serve --quiet` which uses Eleventy's own server, and watches files - intended for development.
* `npm run build` – builds a static version of the website, intended for use with static hosting like Fastly or GitHub Pages

Probably we should document this more though? And perhaps give some guidance on the 2 different ways to host? (Not sure what the pros and cons are, presumably static hosting is cheaper?)

Thoughts @paulrobertlloyd?

**Comment by paulrobertlloyd** [comment]
Just for clarification:

* `govuk-eleventy-plugin` - provides configuration, layouts, components and styles for creating documentation sites using Eleventy
* `govuk-design-history` - uses this plugin, but provides additional layouts and components for showing a list of screenshots and including email examples in posts, as well as scripts to generate screenshots/posts.

The differences in npm script names catches me out sometimes too, and it’s something I’ve tried to keep consistent across different projects, but that tends to mean these often don’t make sense in terms of individual projects.

As Frankie outlined above, there are 3 scripts in this project. Each serve a different purpose and are designed to support different hosting options, as well as local development. Unfortunately, Heroku doesn’t allow hosting of purely static sites, so we have to provide it with a server instance which then serves the static files 🙃 Not sure there are any specific pros and cons, but always good to offer a choice and work against the industry’s tenancy to produce monopolies around these things… `</rant>`

There‘s a bit of [information about the 2 different hosting methods here](https://design-history.herokuapp.com/set-up-a-design-history/#launch), but it could probably be made clearer. And perhaps the README.md is a good place to explain the different npm scripts (the above would be a good place to start).

**Comment by frankieroberto** [comment]
Perhaps `npm start` should run the dev script, and we could have a separate script (`npm run serve-static`?) for Heroku and similar dynamic hosts?

**Comment by jesseyuen** [comment]
Thanks both!

**Comment by paulrobertlloyd** [comment]
Fixed in #159.
