### ISSUE TITLE
Split boilerplate install from example site

### ISSUE THREAD

**Issue by paulrobertlloyd** [fofr/govuk-design-history#192]
(Following discussion in #191)

Much like the Prototype Kit, this repo currently serves several purposes:

* Documentation
* Example site
* Boilerplate template repo for starting your own history

This might cause confusion, and makes it more difficult to make changes to the documentation site that would then impact the boilerplate.

We should consider splitting the project into 2 parts:

* Documentation site
* Boilerplate template repo

Not sure how/where a demo history should live, but maybe that use case is served by pointing to existing histories?

**Comment by paulrobertlloyd** [comment]
Also for consideration: moving the example/documentation site of from Heroku, which @fofr is now paying for.

**Comment by paulrobertlloyd** [comment]
I’ve created a new repository, reused the documentation styles we’ve used for other X-GOVUK sites, and created a documentation site for this project here: <https://x-govuk.github.io/govuk-design-history-docs>

Have lightly edited page titles/descriptions, and added a directory of design histories, the idea being this list can be removed from the template repos `README.md`, and removes the need to have an example site hosted on Heroku.

Benefits of having a separate site are:

* we can update the document site separate to the template repo
* the branding can further move away from that used by GDS, making it clearer this is not a GDS-supported project
* I can draw a new homepage illustration 😉

Downsides of having a separate site are:

* one more repo/project to maintain
* the URL is <https://x-govuk.github.io/govuk-design-history-docs> (ends with `-docs`).

These last 2 issues could be resolved if we host the design history documentation in the `x-govuk.github.io` repo; might that be crossing the streams? I’m minded to do that if only to reduce maintenance overhead, but let me know what you think.

## Next steps

- [x] Decide if separation should proceed
- [x] If so, decide where documentation should live (separate repo, or within organisation repo)
- [x] Remove documentation from template repo, leaving only the example page, and include links to documentation website
- [x] Decommission example design history currently hosted on Heroku


@frankieroberto @fofr Thoughts?

**Comment by frankieroberto** [comment]
@paulrobertlloyd this is great! I think we should go ahead with the separation.

I'm happy with the docs being in a separate repo. I don't think the URL matters too much, and having it in a separate repo might be a bit cleaner and allow the project to be more easily separated from `x-govuk` in future (on the off-chance that it becomes more official!)

Having a smaller, simpler template repo should be great for new users too.

**Comment by frankieroberto** [comment]
@paulrobertlloyd one issue to fix: the `https://x-govuk.github.io` homepage now has a broken link to the "GOV.UK Design History Docs"...

**Comment by paulrobertlloyd** [comment]
Another option is to rename the `govuk-design-history-docs` repo to `govuk-design-history`, and rename the `govuk-design-history` to something like `govuk-design-history-template`.

**Comment by paulrobertlloyd** [comment]
> one issue to fix: the https://x-govuk.github.io homepage now has a broken link to the "GOV.UK Design History Docs"...

Oooh, that list is automatically generated! Need to remember how I did that…

**Comment by frankieroberto** [comment]
> > one issue to fix: the https://x-govuk.github.io homepage now has a broken link to the "GOV.UK Design History Docs"...
> 
> Oooh, that list is automatically generated! Need to remember how I did that…

Yeah I had a quick look, but it was more complicated than I was quickly able to fix... 😉

**Comment by frankieroberto** [comment]
> Another option is to rename the `govuk-design-history-docs` repo to `govuk-design-history`, and rename the `govuk-design-history` to something like `govuk-design-history-template`.

Sounds good to me.
