### ISSUE TITLE
Heading width has gone wrong

### ISSUE THREAD

**Issue by philSNHS** [fofr/govuk-design-history#294]
Something has changed in the last week or so that is affecting the width of the heading area - see attached screen shot - this used to be full width
![Screenshot 2024-06-04 163505](https://github.com/x-govuk/govuk-design-history-template/assets/170538392/b36e14ac-7c31-4019-9b77-b8490b80467d)

**Comment by frankieroberto** [comment]
@philSNHS hiya - thanks for reporting this! 😬 I can't seem to reproduce your screenshot at all. Would you mind checking if it's still an issue, and if so, let us know which browser and platform (Windows/Mac/etc) you’re using?

**Comment by philSNHS** [comment]
Hi @frankieroberto, this is the weirdest thing, it's now working absolutely fine. Yesterday it was as per the screen shot - both the main design history site (as per screen shot) and our project's specific design history site locally on my machine and in Heroku. 

Anyway, all seems to be working ok now, I can only assume my browser (Chrome, Windows) was having a bad day, but seemed odd that it was all 3 versions that I looked at that had the same rendering problem.

**Comment by frankieroberto** [comment]
@philSNHS ah, weird! Thanks for reporting it anyway, and let us know if it happens again!

Great that you’re using this design history template for your project! Can you share a link?

Let us know if there’s anything else you spot, or if you have any ideas for new features!

**Comment by philSNHS** [comment]
Hi @frankieroberto, sorry link to our site is here: https://manage-vac-camp-design-history-edfe2cc6292d.herokuapp.com/

There's no real content in there yet, but hoping to start populating it soon
