### ISSUE TITLE
change engine to "node": "^18.17.1 || >=20.10.0" 

### ISSUE THREAD

**Issue by vickytnz** [fofr/govuk-design-history#299]
I tried to run this but got the error:

> URL.canParse is not a function 

On some searching is is because the node version needs to be 18.17.1 or higher  https://github.com/nodejs/corepack/pull/359#pullrequestreview-1881042380 (which I didn't have) - however the package suggests  

Node guidance would mean making the engine

`"node": "^18.17.1 || >=20.10.0"`

**Comment by frankieroberto** [comment]
@vickytnz good spot!

This template has `govuk-eleventy-plugin` as a dependency which specified `"node": ">=18.17"` as its engine, so I'll update it to that for now.


Incidentally, if you run `npm install` with node `18.16.0` or below you should get this helpful-ish warning (but it’s only a warning so can be ignored):

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@x-govuk/govuk-eleventy-plugin@6.2.4',
npm WARN EBADENGINE   required: { node: '>=18.17' },
npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '9.8.1' }
npm WARN EBADENGINE }
```
